### ISSUE TITLE
Multiple selector.multiList() doesn't work

### ISSUE THREAD

**Issue by dpiffard** [koopaconan/multi-list#1]
Hi, 
I have a problem when I tried to load \<li> elements by ajax then call multiList().
The first time ajax is called it renders correctly the list, but if I tried to update again the \<li> elements 
dynamically using $("#mylist").html("\<li>....</li>") then recall $("#mylist").multiList()  it doesn't render.
Thx for your help.
Denis

**Comment by theisolinearchip** [comment]
Hello!

Since the `.multiList()` call modifies the current list and also adds a couple of new elements outside them (the filter and a hidden field for the selected elements) you should destroy the current `<ul>` with the Remove method (`$("<ul>").multiList("remove");`) and then, **after** that, build a new `<ul>` and call  `$("<ul>").multiList();`.

Hope it helps!

**Comment by dpiffard** [comment]
Thanks for your answer, it works.
Rgds
